spring.application.name=hospital


spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
management.endpoint.health.show-details=always
spring.sql.init.mode=always